CREATE TABLE IF NOT EXISTS `fuel_history` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `car_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `liters` DECIMAL(10,2) NOT NULL,
  `price_per_liter` DECIMAL(10,2) NOT NULL,
  `total_cost` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`car_id`) REFERENCES `cars`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `car_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `liters` DECIMAL(10,2) NOT NULL,
  `price_per_liter` DECIMAL(10,2) NOT NULL,
  `total_cost` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`car_id`) REFERENCES `cars`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 
 